language: java

jdk:

  - oraclejdk1.8

script:

  - java java -classpath Copia\copia2\cASpER-master\Code\out\production\classes\;Copia\copia2\cASpER-master\Code\lib\* it.unisa.casper.cli.CommandLineCasper HELLOWORLD