language: java

jdk:

  - oraclejdk14

script:

  - java -jar Copia/copia2/cASpER-master/Code/build/libs/casper-1.1.2.jar HELLOWORLD

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: main