language: java

jdk:

  - oraclejdk14

script:

  - java -classpath Copia\copia2\cASpER-master\Code\out\production\classes\;Copia\copia2\cASpER-master\Code\lib\* it.unisa.casper.cli.CommandLineCasper HELLOWORLD